spring.application.name=cinematch-backend
# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/cinematch
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=cinematch_secret_key_debe_tener_al_menos_32_caracteres
jwt.expiration=86400000

# WebSocket
spring.websocket.max-text-message-size=8192

# OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Puerto
server.port=8080