spring.application.name=cinematch-backend

# ══ BASE DE DATOS (credenciales directas en dev) ═════════
spring.datasource.url=jdbc:postgresql://localhost:5432/cinematch
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.connection-timeout=20000

# ══ JPA ══════════════════════════════════════════════════
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ══ JWT ══════════════════════════════════════════════════
jwt.secret=cinematch_secret_key_debe_tener_al_menos_32_caracteres
jwt.expiration=86400000

# ══ WEBSOCKET ════════════════════════════════════════════
spring.websocket.max-text-message-size=8192

# ══ OPENAPI (solo útil en dev) ═══════════════════════════
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ══ SERVIDOR ═════════════════════════════════════════════
server.port=8080
server.tomcat.threads.max=50
server.tomcat.threads.min-spare=10
server.tomcat.connection-timeout=20000

# ══ LOGGING ══════════════════════════════════════════════
#logging.config=classpath:log4j2.xml
logging.level.org.springframework=INFO

#Hora
